import { createAsyncThunk, createSlice,PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../../store";
import { IttoType } from "../../../types/pmp";
import axios from "axios";

export interface ittoListState {
  value: Array<IttoType>;
  processId: string;
  status: "idle" | "loading" | "failed";
}

const initialState: ittoListState = {
  value: [],
  processId:'',
  status: "idle",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const ittoListAsync = createAsyncThunk(
  "ittoList",
  async (id:string) => 
  {
    const response = await axios.get<string>(`/csv/pmp/itto/itto_${id}.csv`);
    const dataArray:string[][] = [];
    const dataString = response.data.split("\n");
    const ittoList:Array<IttoType> = []
    for (let row = 0; row < dataString.length; row++) {
      dataArray[row] = dataString[row].split(",");
      console.log(dataArray[row].length);

      for (let col = 0; col < dataArray[row].length; col = col+4) {
        const itto:IttoType = {
          id:dataArray[row][col+0],
          input:dataArray[row][col+1],
          tool:dataArray[row][col+2],
          output:dataArray[row][col+3]
        }
        ittoList.push(itto)
      }
    }

    // The value we return becomes the `fulfilled` action payload
    return ittoList;
  }
);

export const ittoListSlice = createSlice({
  name: "ittoList",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setProcessId: (state, action:PayloadAction<string>) => {
      state.processId = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(ittoListAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(ittoListAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.value = action.payload;
      });
  },
});
export const {setProcessId} = ittoListSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectIttoListState = (state: RootState): ittoListState =>state.itto;

export default ittoListSlice.reducer;
